/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Main extends javax.swing.JFrame {
    String hargaLap = "", lamaSewa = "";
    int biayaLap = 0, hargaTambahanSewa = 0, totalHarga = 0, kembalian = 0;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(this);
    }
    
    public static boolean cekOnlyNumbers(String txt){
        String rgx = "^[0-9]+$";
        
        return txt.matches(rgx);
    }
    
    public static boolean cekOnlyWords(String txt) {
        String rgx = "^[A-Za-z]+$";
        return txt.matches(rgx);
    }
    
    public String getBiayaLap(){
        
        String jenisLap = cmbJenisLap.getSelectedItem().toString();
        
        if(cmbJenisLap.getSelectedIndex() != 0) {
            
            if(rbIndoor.isSelected()) {
                
                switch(jenisLap) {
                    case "Reguler":
                        this.hargaLap = "300000";
                        break;
                    case "Matras":
                        this.hargaLap = "250000";
                        break;
                    case "Rumput":
                        this.hargaLap = "200000";
                        break;
                }
                
                
            } else if(rbOutdoor.isSelected()) {
                
                switch(jenisLap) {
                    case "Reguler":
                        this.hargaLap = "250000";
                        break;
                    case "Matras":
                        this.hargaLap = "200000";
                        break;
                    case "Rumput":
                        this.hargaLap = "150000";
                        break;
                }
            }
            
        } else {
            this.hargaLap = "-";
        }
        
        return this.hargaLap;
    }
    
    public void setHargaLap() {
        String hargaLapTemp = "- / JAM";
        String biaya = (!this.getBiayaLap().equals("-")) ? formatRp(this.getBiayaLap()) : this.getBiayaLap();
        labelHargaLap.setText(biaya + hargaLapTemp.substring(1));
    }
    
    public void setBiayaLap() {
       int lamaSewaTemp = (!this.lamaSewa.isEmpty() && cekOnlyNumbers(this.lamaSewa)) 
               ? Integer.parseInt(this.lamaSewa)
               : 0;
       int hargaLapTemp = (!this.hargaLap.isEmpty() && cekOnlyNumbers(this.hargaLap))? Integer.parseInt(this.hargaLap) : 0;
       this.biayaLap = lamaSewaTemp * hargaLapTemp;
       
       txtBiayaLap.setText(formatRp(String.valueOf(this.biayaLap)));
    }
    
    public void setHargaTambahanSewa() {
        int lamaSewaTemp = (!this.lamaSewa.isEmpty() && cekOnlyNumbers(this.lamaSewa)) 
               ? Integer.parseInt(this.lamaSewa)
               : 0;
        int sepatu = (cbSewaSepatu.isSelected()) ? 50000 : 0,
            kostum = (cbSewaKostum.isSelected()) ? 45000 : 0;
        this.hargaTambahanSewa = lamaSewaTemp * (sepatu + kostum);
        
        txtHargaTambahanSewa.setText(formatRp(String.valueOf(this.hargaTambahanSewa)));
    }
    
    public void setTotalHarga() {
        this.totalHarga = this.biayaLap + this.hargaTambahanSewa;
        txtTotalHarga.setText(formatRp(String.valueOf(this.totalHarga)));
    }
    
    public void resetTotalHarga(){
        this.totalHarga = 0;
        txtTotalHarga.setText("0");
        txtUangKembalian.setText("-");
    }
    
    public String formatRp(String r) {
        Double a;
        a = Double.parseDouble(r);
        
        NumberFormat nf = NumberFormat.getNumberInstance(new Locale("in", "ID"));
        return nf.format(a);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbTipeLap = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelHeader = new javax.swing.JLabel();
        labelNamaPenyewa = new javax.swing.JLabel();
        txtNamaPenyewa = new javax.swing.JTextField();
        labelNoTelp = new javax.swing.JLabel();
        txtNoTelp = new javax.swing.JTextField();
        labelLamaSewa = new javax.swing.JLabel();
        txtLamaSewa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        labelHeaderLap = new javax.swing.JLabel();
        labelTipeLap = new javax.swing.JLabel();
        rbIndoor = new javax.swing.JRadioButton();
        rbOutdoor = new javax.swing.JRadioButton();
        labelJenisLap = new javax.swing.JLabel();
        cmbJenisLap = new javax.swing.JComboBox<>();
        labelHargaLap = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelHeaderTambahanSewa = new javax.swing.JLabel();
        cbSewaSepatu = new javax.swing.JCheckBox();
        txtSewaSepatu = new javax.swing.JTextField();
        cbSewaKostum = new javax.swing.JCheckBox();
        txtSewaKostum = new javax.swing.JTextField();
        btnResetTambahanSewa = new javax.swing.JButton();
        btnSelectAllTambahanSewa = new javax.swing.JButton();
        btnUlang = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnCetakStruk = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        labelHeaderDetailOrder = new javax.swing.JLabel();
        labelOrderTipeLap = new javax.swing.JLabel();
        labelOrderJenisLap = new javax.swing.JLabel();
        txtOrderTipeLap = new javax.swing.JTextField();
        txtOrderJenisLap = new javax.swing.JTextField();
        labelOrderDurasi = new javax.swing.JLabel();
        txtOrderDurasi = new javax.swing.JTextField();
        labelDurasiJam = new javax.swing.JLabel();
        labelOrderTambahanSewa = new javax.swing.JLabel();
        cbOrderSewaSepatu = new javax.swing.JCheckBox();
        cbOrderSewaKostum = new javax.swing.JCheckBox();
        labelHeaderDetailHargaSewa = new javax.swing.JLabel();
        labelBiayaLap = new javax.swing.JLabel();
        txtBiayaLap = new javax.swing.JTextField();
        labelHargaTambahanSewa = new javax.swing.JLabel();
        txtHargaTambahanSewa = new javax.swing.JTextField();
        txtTotalHarga = new javax.swing.JTextField();
        labelTotalHarga = new javax.swing.JLabel();
        labelHeaderPembayaran = new javax.swing.JLabel();
        labelUangBayar = new javax.swing.JLabel();
        txtUangBayar = new javax.swing.JTextField();
        labelUangKembalian = new javax.swing.JLabel();
        txtUangKembalian = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        labelHeader.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelHeader.setText("FUTSAL CENTER HAFIDZ");

        labelNamaPenyewa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelNamaPenyewa.setText("Nama Penyewa");

        labelNoTelp.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelNoTelp.setText("No Telp");

        labelLamaSewa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelLamaSewa.setText("Lama Sewa (JAM)");

        txtLamaSewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLamaSewaKeyReleased(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        labelHeaderLap.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelHeaderLap.setForeground(new java.awt.Color(153, 153, 255));
        labelHeaderLap.setText("LAPANGAN");

        labelTipeLap.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelTipeLap.setText("Tipe Lapangan");

        rbTipeLap.add(rbIndoor);
        rbIndoor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbIndoor.setText("Indoor");
        rbIndoor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbIndoor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIndoorActionPerformed(evt);
            }
        });

        rbTipeLap.add(rbOutdoor);
        rbOutdoor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbOutdoor.setText("Outdoor");
        rbOutdoor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbOutdoor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOutdoorActionPerformed(evt);
            }
        });

        labelJenisLap.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelJenisLap.setText("Jenis Lapangan");

        cmbJenisLap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbJenisLap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "==== Pilih Jenis Lapangan ====", "Reguler", "Matras", "Rumput" }));
        cmbJenisLap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbJenisLap.setEnabled(false);
        cmbJenisLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJenisLapActionPerformed(evt);
            }
        });

        labelHargaLap.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelHargaLap.setText("- / JAM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelHargaLap)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbIndoor)
                                .addGap(18, 18, 18)
                                .addComponent(rbOutdoor))
                            .addComponent(labelTipeLap)
                            .addComponent(labelJenisLap)
                            .addComponent(cmbJenisLap, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(labelHeaderLap)
                        .addGap(89, 89, 89))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelHeaderLap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTipeLap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbIndoor)
                    .addComponent(rbOutdoor))
                .addGap(18, 18, 18)
                .addComponent(labelJenisLap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbJenisLap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelHargaLap)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        labelHeaderTambahanSewa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelHeaderTambahanSewa.setForeground(new java.awt.Color(153, 153, 255));
        labelHeaderTambahanSewa.setText("TAMBAHAN SEWA");

        cbSewaSepatu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbSewaSepatu.setText("Sepatu");
        cbSewaSepatu.setEnabled(false);
        cbSewaSepatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSewaSepatuActionPerformed(evt);
            }
        });

        txtSewaSepatu.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtSewaSepatu.setText("-");
        txtSewaSepatu.setEnabled(false);

        cbSewaKostum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbSewaKostum.setText("Kostum");
        cbSewaKostum.setEnabled(false);
        cbSewaKostum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSewaKostumActionPerformed(evt);
            }
        });

        txtSewaKostum.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtSewaKostum.setText("-");
        txtSewaKostum.setEnabled(false);

        btnResetTambahanSewa.setBackground(new java.awt.Color(153, 153, 255));
        btnResetTambahanSewa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnResetTambahanSewa.setForeground(new java.awt.Color(255, 255, 255));
        btnResetTambahanSewa.setText("Reset");
        btnResetTambahanSewa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetTambahanSewa.setEnabled(false);
        btnResetTambahanSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetTambahanSewaActionPerformed(evt);
            }
        });

        btnSelectAllTambahanSewa.setBackground(new java.awt.Color(153, 153, 255));
        btnSelectAllTambahanSewa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSelectAllTambahanSewa.setForeground(new java.awt.Color(255, 255, 255));
        btnSelectAllTambahanSewa.setText("Sewa Semua");
        btnSelectAllTambahanSewa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSelectAllTambahanSewa.setEnabled(false);
        btnSelectAllTambahanSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAllTambahanSewaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(labelHeaderTambahanSewa))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSewaSepatu)
                            .addComponent(txtSewaSepatu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnResetTambahanSewa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSewaKostum)
                            .addComponent(txtSewaKostum, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSelectAllTambahanSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelHeaderTambahanSewa)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSewaSepatu)
                    .addComponent(cbSewaKostum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSewaSepatu)
                    .addComponent(txtSewaKostum, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelectAllTambahanSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetTambahanSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnUlang.setBackground(new java.awt.Color(102, 102, 255));
        btnUlang.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnUlang.setForeground(new java.awt.Color(255, 255, 255));
        btnUlang.setText("Ulang");
        btnUlang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlangActionPerformed(evt);
            }
        });

        btnHitung.setBackground(new java.awt.Color(102, 102, 255));
        btnHitung.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnHitung.setForeground(new java.awt.Color(255, 255, 255));
        btnHitung.setText("Hitung Total");
        btnHitung.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(102, 102, 255));
        btnKeluar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setText("Keluar");
        btnKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnCetakStruk.setBackground(new java.awt.Color(102, 102, 255));
        btnCetakStruk.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnCetakStruk.setForeground(new java.awt.Color(255, 255, 255));
        btnCetakStruk.setText("Cetak Struk Pembayaran");
        btnCetakStruk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCetakStruk.setEnabled(false);
        btnCetakStruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakStrukActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        labelHeaderDetailOrder.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        labelHeaderDetailOrder.setText("========== DETAIL ORDER ==========");

        labelOrderTipeLap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelOrderTipeLap.setText("TIPE LAPANGAN");

        labelOrderJenisLap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelOrderJenisLap.setText("JENIS LAPANGAN");

        txtOrderTipeLap.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtOrderTipeLap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOrderTipeLap.setText("-");
        txtOrderTipeLap.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 2, true));
        txtOrderTipeLap.setEnabled(false);

        txtOrderJenisLap.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtOrderJenisLap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOrderJenisLap.setText("-");
        txtOrderJenisLap.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 2, true));
        txtOrderJenisLap.setEnabled(false);

        labelOrderDurasi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelOrderDurasi.setText("DURASI");

        txtOrderDurasi.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtOrderDurasi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOrderDurasi.setText("-");
        txtOrderDurasi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 2, true));
        txtOrderDurasi.setEnabled(false);

        labelDurasiJam.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        labelDurasiJam.setText("JAM");

        labelOrderTambahanSewa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelOrderTambahanSewa.setText("TAMBAHAN SEWA");

        cbOrderSewaSepatu.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbOrderSewaSepatu.setText("Sepatu");
        cbOrderSewaSepatu.setEnabled(false);

        cbOrderSewaKostum.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cbOrderSewaKostum.setText("Kostum");
        cbOrderSewaKostum.setEnabled(false);

        labelHeaderDetailHargaSewa.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        labelHeaderDetailHargaSewa.setText("========== DETAIL HARGA SEWA ==========");

        labelBiayaLap.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelBiayaLap.setText("Biaya Lapangan");

        txtBiayaLap.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtBiayaLap.setText("0");
        txtBiayaLap.setEnabled(false);

        labelHargaTambahanSewa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelHargaTambahanSewa.setText("Harga Tambahan Sewa");

        txtHargaTambahanSewa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtHargaTambahanSewa.setText("0");
        txtHargaTambahanSewa.setEnabled(false);

        txtTotalHarga.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtTotalHarga.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalHarga.setText("0");
        txtTotalHarga.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 2, true));
        txtTotalHarga.setEnabled(false);

        labelTotalHarga.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelTotalHarga.setText("Total Harga");

        labelHeaderPembayaran.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        labelHeaderPembayaran.setText("========== PEMBAYARAN ==========");

        labelUangBayar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelUangBayar.setText("Uang Bayar");

        txtUangBayar.setBackground(new java.awt.Color(204, 204, 255));
        txtUangBayar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtUangBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUangBayarKeyReleased(evt);
            }
        });

        labelUangKembalian.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        labelUangKembalian.setText("Uang Kembalian");

        txtUangKembalian.setBackground(new java.awt.Color(204, 204, 255));
        txtUangKembalian.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtUangKembalian.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUangKembalian.setText("-");
        txtUangKembalian.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(labelHeaderDetailHargaSewa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtOrderDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelOrderDurasi))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelDurasiJam))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelOrderTambahanSewa)
                                .addGap(75, 75, 75))))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOrderTipeLap, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(labelOrderTipeLap)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(labelOrderJenisLap)
                                .addGap(79, 79, 79))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOrderJenisLap, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(cbOrderSewaSepatu)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbOrderSewaKostum)))
                                .addGap(19, 19, 19))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(labelHeaderDetailOrder))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelUangBayar))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelUangKembalian)
                                    .addComponent(txtUangKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(labelTotalHarga)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(labelHargaTambahanSewa)
                                    .addGap(37, 37, 37)
                                    .addComponent(txtHargaTambahanSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(labelBiayaLap)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtBiayaLap, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(labelHeaderPembayaran)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelHeaderDetailOrder)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOrderTipeLap)
                    .addComponent(labelOrderJenisLap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrderTipeLap, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrderJenisLap, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOrderDurasi)
                    .addComponent(labelOrderTambahanSewa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrderDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDurasiJam)
                    .addComponent(cbOrderSewaSepatu)
                    .addComponent(cbOrderSewaKostum))
                .addGap(18, 18, 18)
                .addComponent(labelHeaderDetailHargaSewa)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBiayaLap)
                    .addComponent(txtBiayaLap, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHargaTambahanSewa)
                    .addComponent(txtHargaTambahanSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalHarga)
                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelHeaderPembayaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUangBayar)
                    .addComponent(labelUangKembalian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUangKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelLamaSewa)
                                .addComponent(txtLamaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelNamaPenyewa)
                                .addComponent(txtNamaPenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelNoTelp)
                                .addComponent(txtNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(btnUlang, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnCetakStruk, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelHeader)
                .addGap(443, 443, 443))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelHeader)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelNamaPenyewa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNamaPenyewa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelNoTelp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(labelLamaSewa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLamaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUlang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCetakStruk, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLamaSewaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLamaSewaKeyReleased
        this.lamaSewa = txtLamaSewa.getText().trim();
        txtOrderDurasi.setText((!this.lamaSewa.isEmpty() && cekOnlyNumbers(this.lamaSewa)) ? this.lamaSewa : "-");
        
        if(!this.lamaSewa.isEmpty() && cekOnlyNumbers(this.lamaSewa)) {
            cbSewaSepatu.setEnabled(true);
            cbSewaKostum.setEnabled(true);
            btnResetTambahanSewa.setEnabled(true);
            btnSelectAllTambahanSewa.setEnabled(true);
        } else {
            cbSewaSepatu.setEnabled(false);
            cbSewaKostum.setEnabled(false);
            btnResetTambahanSewa.setEnabled(false);
            btnSelectAllTambahanSewa.setEnabled(false);
        }
        
        this.setBiayaLap();
        this.setHargaTambahanSewa();
        this.resetTotalHarga();
    }//GEN-LAST:event_txtLamaSewaKeyReleased

    private void rbIndoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIndoorActionPerformed
        if(rbIndoor.isSelected()) {
            txtOrderTipeLap.setText(rbIndoor.getText().toUpperCase());
        } else {
            txtOrderTipeLap.setText("-");
        }
        
        cmbJenisLap.setSelectedIndex(0);
        cmbJenisLap.setEnabled(true);
        this.resetTotalHarga();
    }//GEN-LAST:event_rbIndoorActionPerformed

    private void rbOutdoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOutdoorActionPerformed
        if(rbOutdoor.isSelected()) {
            txtOrderTipeLap.setText(rbOutdoor.getText().toUpperCase());
        } else {
            txtOrderTipeLap.setText("-");
        }
        
        cmbJenisLap.setSelectedIndex(0);
        cmbJenisLap.setEnabled(true);
        this.resetTotalHarga();
    }//GEN-LAST:event_rbOutdoorActionPerformed

    private void cmbJenisLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJenisLapActionPerformed
        txtOrderJenisLap.setText((cmbJenisLap.getSelectedIndex() != 0) 
                    ? cmbJenisLap.getSelectedItem().toString().toUpperCase()
                    : "-");
        this.setHargaLap();
        this.setBiayaLap();
        this.resetTotalHarga();
    }//GEN-LAST:event_cmbJenisLapActionPerformed

    private void btnUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlangActionPerformed
        txtNamaPenyewa.setText("");
        txtNoTelp.setText("");
        txtLamaSewa.setText("");
        rbTipeLap.clearSelection();
        cmbJenisLap.setSelectedIndex(0);
        cmbJenisLap.setEnabled(false);
        txtOrderTipeLap.setText("-");
        txtOrderDurasi.setText("-");
        cbSewaSepatu.setEnabled(false);
        cbSewaKostum.setEnabled(false);
        cbSewaSepatu.setSelected(false);
        cbSewaKostum.setSelected(false);
        cbOrderSewaSepatu.setSelected(false);
        cbOrderSewaKostum.setSelected(false);
        btnResetTambahanSewa.setEnabled(false);
        btnSelectAllTambahanSewa.setEnabled(false);
        txtSewaSepatu.setText("-");
        txtSewaKostum.setText("-");
        txtHargaTambahanSewa.setText("0");
        this.resetTotalHarga();
        txtUangBayar.setText("");
        txtUangKembalian.setText("-");
        btnCetakStruk.setEnabled(false);
    }//GEN-LAST:event_btnUlangActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin keluar?", "PERTANYAAN", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            
            JOptionPane.showMessageDialog(this, "Terima Kasih!", "PESAN",JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
            
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void cbSewaSepatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSewaSepatuActionPerformed
        cbOrderSewaSepatu.setSelected(cbSewaSepatu.isSelected());
        txtSewaSepatu.setText((cbSewaSepatu.isSelected()) ? "50.000 / JAM" : "-");
        this.setHargaTambahanSewa();
        this.resetTotalHarga();
    }//GEN-LAST:event_cbSewaSepatuActionPerformed

    private void cbSewaKostumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSewaKostumActionPerformed
        cbOrderSewaKostum.setSelected(cbSewaKostum.isSelected());
        txtSewaKostum.setText((cbSewaKostum.isSelected())? "45.000 / JAM" : "-");
        this.setHargaTambahanSewa();
        this.resetTotalHarga();
    }//GEN-LAST:event_cbSewaKostumActionPerformed

    private void btnSelectAllTambahanSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAllTambahanSewaActionPerformed
        cbSewaSepatu.setSelected(true);
        cbSewaKostum.setSelected(true);
        txtSewaSepatu.setText("50.000 / JAM");
        txtSewaKostum.setText("45.000 / JAM");
        cbOrderSewaSepatu.setSelected(true);
        cbOrderSewaKostum.setSelected(true);
        this.setHargaTambahanSewa();
        this.resetTotalHarga();
    }//GEN-LAST:event_btnSelectAllTambahanSewaActionPerformed

    private void btnResetTambahanSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetTambahanSewaActionPerformed
        cbSewaSepatu.setSelected(false);
        cbSewaKostum.setSelected(false);
        txtSewaSepatu.setText("-");
        txtSewaKostum.setText("-");
        cbOrderSewaSepatu.setSelected(false);
        cbOrderSewaKostum.setSelected(false);
        this.setHargaTambahanSewa();
        this.resetTotalHarga();
    }//GEN-LAST:event_btnResetTambahanSewaActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
       if(!this.lamaSewa.isEmpty() && cekOnlyNumbers(this.lamaSewa)) {
           this.setTotalHarga();
           if(!txtUangBayar.getText().isEmpty()) {
               
            int uangBayar = (!txtUangBayar.getText().isEmpty()) ? Integer.parseInt(txtUangBayar.getText().trim()) : 0;
            if(uangBayar == 0) {
                txtUangKembalian.setText("-");
                return;
            }
            
            int kembalianTemp = uangBayar - this.totalHarga;
            
            if(kembalianTemp < 0) {
                txtUangKembalian.setText("Maaf uang anda tidak cukup!");
            } else if(kembalianTemp == 0) {
                txtUangKembalian.setText("-");
            } else {
                this.kembalian = kembalianTemp;
                txtUangKembalian.setText(formatRp(String.valueOf(kembalian)));
            }
               
           }
           
       } else {
           JOptionPane.showMessageDialog(this, "Mohon masukkan lama sewa terlebih dahulu!!", "ERROR", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void txtUangBayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUangBayarKeyReleased
        if(txtTotalHarga.getText().equals("0")) {
            
            JOptionPane.showMessageDialog(this, "Hitung total harga terlebih dahulu!!", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtUangBayar.setText("");
            btnCetakStruk.setEnabled(false);
            
        } else {
            
           if(!txtUangBayar.getText().isEmpty() && !cekOnlyNumbers(txtUangBayar.getText().trim())) {
               
               JOptionPane.showMessageDialog(this, "Uang bayar harus berupa angka!!", "ERROR", JOptionPane.ERROR_MESSAGE);
               txtUangBayar.setText("");
               btnCetakStruk.setEnabled(false);
               return;
           }
            
            int uangBayar = (!txtUangBayar.getText().isEmpty()) ? Integer.parseInt(txtUangBayar.getText().trim()) : 0;
            if(uangBayar == 0) {
                txtUangKembalian.setText("-");
                btnCetakStruk.setEnabled(false);
                return;
            }
            
            btnCetakStruk.setEnabled(true);
            
            int kembaliantemp = uangBayar - this.totalHarga;
            
            if(kembaliantemp < 0) {
                txtUangKembalian.setText("Maaf uang anda tidak cukup!");
            } else if(kembaliantemp == 0) {
                txtUangKembalian.setText("-");
            } else {
                this.kembalian = kembaliantemp;
                txtUangKembalian.setText(formatRp(String.valueOf(kembalian)));
            }
            
        }
    }//GEN-LAST:event_txtUangBayarKeyReleased

    private void btnCetakStrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakStrukActionPerformed
        if(txtUangKembalian.getText().equals("Maaf uang anda tidak cukup!")) {
            JOptionPane.showMessageDialog(this, "Pembayaran Gagal! Uang anda tidak cukup!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(txtTotalHarga.getText().equals("0")) {
            JOptionPane.showMessageDialog(this, "Hitung total harga terlebih dahulu!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(txtNamaPenyewa.getText().trim().isEmpty() && txtNoTelp.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lengkapi data anda dengan benar!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            
            if(!cekOnlyWords(txtNamaPenyewa.getText().trim())) {
                JOptionPane.showMessageDialog(this, "Nama penyewa tidak boleh mengandung angka!", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if(!cekOnlyNumbers(txtNoTelp.getText().trim())) {
                JOptionPane.showMessageDialog(this, "No Telp harus berupa angka!", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        Struk struk = new Struk();
        
        
        String nama = txtNamaPenyewa.getText().trim();
        String notelp = txtNoTelp.getText().trim();
        String durasi = txtOrderDurasi.getText().trim();
        
        String tipe = "";
        if(rbIndoor.isSelected()) tipe = "INDOOR";
        if(rbOutdoor.isSelected()) tipe = "OUTDOOR";
        if(!rbIndoor.isSelected() && !rbOutdoor.isSelected()) tipe = "-";
        
        String jenis = (cmbJenisLap.getSelectedIndex() != 0) ?  cmbJenisLap.getSelectedItem().toString().toUpperCase() : "-";
        String hargaLapTemp = (this.biayaLap == 0) ? "-" : String.valueOf(this.biayaLap);
        
        struk.setData(nama,notelp,durasi,tipe,jenis, cbSewaSepatu.isSelected(), cbSewaKostum.isSelected(),
                hargaLapTemp, String.valueOf(this.hargaTambahanSewa), String.valueOf(this.totalHarga),
                txtUangBayar.getText().trim(), String.valueOf(this.kembalian));
        
        struk.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCetakStrukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetakStruk;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnResetTambahanSewa;
    private javax.swing.JButton btnSelectAllTambahanSewa;
    private javax.swing.JButton btnUlang;
    private javax.swing.JCheckBox cbOrderSewaKostum;
    private javax.swing.JCheckBox cbOrderSewaSepatu;
    private javax.swing.JCheckBox cbSewaKostum;
    private javax.swing.JCheckBox cbSewaSepatu;
    private javax.swing.JComboBox<String> cmbJenisLap;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelBiayaLap;
    private javax.swing.JLabel labelDurasiJam;
    private javax.swing.JLabel labelHargaLap;
    private javax.swing.JLabel labelHargaTambahanSewa;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelHeaderDetailHargaSewa;
    private javax.swing.JLabel labelHeaderDetailOrder;
    private javax.swing.JLabel labelHeaderLap;
    private javax.swing.JLabel labelHeaderPembayaran;
    private javax.swing.JLabel labelHeaderTambahanSewa;
    private javax.swing.JLabel labelJenisLap;
    private javax.swing.JLabel labelLamaSewa;
    private javax.swing.JLabel labelNamaPenyewa;
    private javax.swing.JLabel labelNoTelp;
    private javax.swing.JLabel labelOrderDurasi;
    private javax.swing.JLabel labelOrderJenisLap;
    private javax.swing.JLabel labelOrderTambahanSewa;
    private javax.swing.JLabel labelOrderTipeLap;
    private javax.swing.JLabel labelTipeLap;
    private javax.swing.JLabel labelTotalHarga;
    private javax.swing.JLabel labelUangBayar;
    private javax.swing.JLabel labelUangKembalian;
    private javax.swing.JRadioButton rbIndoor;
    private javax.swing.JRadioButton rbOutdoor;
    private javax.swing.ButtonGroup rbTipeLap;
    private javax.swing.JTextField txtBiayaLap;
    private javax.swing.JTextField txtHargaTambahanSewa;
    private javax.swing.JTextField txtLamaSewa;
    private javax.swing.JTextField txtNamaPenyewa;
    private javax.swing.JTextField txtNoTelp;
    private javax.swing.JTextField txtOrderDurasi;
    private javax.swing.JTextField txtOrderJenisLap;
    private javax.swing.JTextField txtOrderTipeLap;
    private javax.swing.JTextField txtSewaKostum;
    private javax.swing.JTextField txtSewaSepatu;
    private javax.swing.JTextField txtTotalHarga;
    private javax.swing.JTextField txtUangBayar;
    private javax.swing.JTextField txtUangKembalian;
    // End of variables declaration//GEN-END:variables
}
